hooks
Signed-off-by: Ryan Northey <ryan@synca.io>

diff --git a/support/hooks/pre-push b/support/hooks/pre-push
--- a/support/hooks/pre-push
+++ b/support/hooks/pre-push
@@ -57,11 +57,15 @@ do
     # `$CLANG_FORMAT` and `$BUILDIFY` are defined, or that the default values it
     # assumes for these variables correspond to real binaries on the system. If
     # either of these things aren't true, the check fails.
+    FAILS_FORMAT=
     for i in $(git diff --name-only $RANGE --diff-filter=ACMR --ignore-submodules=all 2>&1); do
-      echo -ne "  Checking format for $i - "
-      "$SCRIPT_DIR"/code_format/check_format.py check $i
-      if [[ $? -ne 0 ]]; then
-        exit 1
+      if [[ -z "$FAILS_FORMAT" ]]; then
+        echo -ne "  Checking format for $i - "
+        "$SCRIPT_DIR"/code_format/check_format.py check $i
+        if [[ $? -ne 0 ]]; then
+          echo "Unable to perform code_format/check_format.py"
+          FAILS_FORMAT=yes
+        fi
       fi
 
       echo "  Checking spelling for $i"
