hooks
Signed-off-by: Ryan Northey <ryan@synca.io>

diff --git a/support/hooks/pre-push b/support/hooks/pre-push
--- a/support/hooks/pre-push
+++ b/support/hooks/pre-push
@@ -65,7 +65,7 @@ do
           exit 1
         fi
       else
-        echo "Missing \$BUILDIFIER_PATH, skipping code_format/check_format.py" 2>&
+        echo "Missing \$BUILDIFIER_PATH, skipping code_format/check_format.py" >&2
       fi
 
       echo "  Checking spelling for $i"
